// ============================================
// ajineshpratapsingh — Data Store
// Updated: June 14, 2026
// ============================================

import type { NewsArticle, ResearchItem, ResearchPaper } from './types';

export const newsArticles: NewsArticle[] = [
  {
    id: 'news-featured',
    title: 'G7 Summit Day 2 LIVE',
    excerpt:
      'G7 summit focuses on contentious future of AI and U.S. dominance of the industry',
    category: 'AI Policy',
    date: 'June 17, 2026',
    readTime: '5 min read',
    featured: true,
    icon: `<svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"><circle cx="12" cy="12" r="10"/><path d="M12 8v4l3 3"/></svg>`,
    url: 'https://www.thehindu.com/news/international/g7-summit-france-day-2-leaders-discuss-west-asia-conflict-ukraine-russia-war-live-updates-june-17-2026/article71111954.ece',
  },
  {
    id: 'news-2',
    title: 'Anthropic Raises at $965B Valuation in Series H, Targets Q2 2026 Operating Profit',
    excerpt:
      'Anthropic closed its Series H at a $965 billion valuation in May 2026, with $44 billion in annualized run-rate revenue. The company is on track for its first operating profit — approximately $559 million — in Q2 2026, ahead of a closely watched IPO.',
    category: 'Industry News',
    date: 'June 8, 2026',
    readTime: '6 min read',
    featured: false,
    icon: `<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"><path d="M12 2L2 7l10 5 10-5-10-5z"/><path d="M2 17l10 5 10-5"/><path d="M2 12l10 5 10-5"/></svg>`,
    url: 'https://www.tradingview.com/news/reuters.com,2026:newsml_L6N42N14H:0-judge-blocks-subpoena-for-chatgpt-records-in-lender-s-lawsuit/',
  },
  {
    id: 'news-3',
    title: 'Judge blocks subpoena for ChatGPT records in lenders lawsuit',
    excerpt:
      'Judge blocks subpoena for ChatGPT records in lenders lawsuit.',
    category: 'Generative AI',
    date: 'June 2026',
    readTime: '5 min read',
    featured: false,
    icon: `<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"><path d="M12 2L2 7l10 5 10-5-10-5z"/><path d="M2 17l10 5 10-5"/><path d="M2 12l10 5 10-5"/></svg>`,
    url: 'https://theaitrack.com/ai-news-june-2026-in-depth-and-concise/',
  },
  {
    id: 'news-4',
    title: 'Google Gemini Omni Flash Brings Native Video Generation to YouTube and Gemini',
    excerpt:
      'Google launched Gemini Omni Flash, integrating multimodal AI video generation and conversational editing directly into Gemini, Flow, YouTube Shorts, and YouTube Create. The release includes avatar creation tools, SynthID watermarking, and C2PA content verification.',
    category: 'Generative AI',
    date: 'June 2026',
    readTime: '4 min read',
    featured: false,
    icon: `<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/><path d="M7 8h2m2 0h2m2 0h2M7 11h6"/></svg>`,
    url: 'https://theaitrack.com/ai-news-june-2026-in-depth-and-concise/',
  },
  {
    id: 'news-5',
    title: 'DeepSeek V4 Pro Slashes Prices by 75%, Strengthening Position in Agentic AI Market',
    excerpt:
      'DeepSeek cut the price of its flagship V4 Pro model by 75%, making it one of the most cost-effective options for long-context AI agents, coding tools, and enterprise workflows. The move intensifies price competition across the LLM market.',
    category: 'Open Source',
    date: 'June 2026',
    readTime: '4 min read',
    featured: false,
    icon: `<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>`,
    url: 'https://theaitrack.com/ai-news-june-2026-in-depth-and-concise/',
  },
  {
    id: 'news-6',
    title: 'SK Hynix Hits $1 Trillion Market Cap as AI Memory Demand Reshapes the Chip Industry',
    excerpt:
      'SK Hynix reached a $1 trillion market capitalization for the first time, joining Samsung and Micron as surging AI memory demand reshapes the global semiconductor landscape. The milestone underscores how HBM and high-bandwidth memory have become central to the AI infrastructure buildout.',
    category: 'Industry News',
    date: 'June 2026',
    readTime: '4 min read',
    featured: false,
    icon: `<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`,
    url: 'https://theaitrack.com/ai-news-june-2026-in-depth-and-concise/',
  },
  {
    id: 'news-7',
    title: 'Quantum-AI Hybrid Systems Show Dramatic Improvements in Chaotic System Predictions',
    excerpt:
      'Researchers have demonstrated that combining quantum computing with AI can significantly improve predictions of complex, chaotic systems. By using a quantum computer to identify hidden patterns in data, AI models become more accurate and stable on tasks that were previously intractable.',
    category: 'Research',
    date: 'June 17, 2026',
    readTime: '5 min read',
    featured: false,
    icon: `<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"><circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>`,
    url: 'https://www.sciencedaily.com/news/computers_math/artificial_intelligence/',
  },
  {
    id: 'news-8',
    title: "Moonshot AI's Kimi Seeks $2B Funding Round at $30B Valuation",
    excerpt:
      'Beijing-based Moonshot AI, creator of the Kimi chatbot, is seeking up to $2 billion in a new funding round that would value the company at $30 billion — its third major financing in just six months, reflecting continued investor appetite for frontier AI labs outside the US.',
    category: 'Industry News',
    date: 'May 2026',
    readTime: '4 min read',
    featured: false,
    icon: `<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>`,
    url: 'https://www.crescendo.ai/news/latest-ai-news-and-updates',
  },
];

export const researchItems: ResearchItem[] = [
  // ── 2025 Papers ──────────────────────────────────────────────
  {
    id: 'research-2025-1',
    title: 'DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning',
    excerpt:
      'DeepSeek introduces R1-Zero and R1, leveraging pure reinforcement learning to cultivate chain-of-thought reasoning without supervised fine-tuning. DeepSeek-R1 performs on par with OpenAI o1 on math, coding, and logical benchmarks.',
    category: 'rl',
    date: 'January 2025',
    source: 'arXiv — 2501.12948',
    tags: ['Reasoning', 'Reinforcement Learning', 'LLM'],
    url: 'https://arxiv.org/abs/2501.12948',
  },
  {
    id: 'research-2025-2',
    title: 'Towards System 2 Reasoning in LLMs: Learning How to Think With Meta Chain-of-Thought',
    excerpt:
      'This paper proposes Meta Chain-of-Thought (Meta-CoT), a framework that teaches LLMs not just to use chain-of-thought but to learn when and how to reason, pushing toward System 2 deliberative thinking in language models.',
    category: 'llm',
    date: 'January 2025',
    source: 'arXiv — 2501.04682',
    tags: ['Chain-of-Thought', 'Reasoning', 'LLM'],
    url: 'https://arxiv.org/abs/2501.04682',
  },
  {
    id: 'research-2025-3',
    title: 'Kimi k1.5: Scaling Reinforcement Learning with LLMs',
    excerpt:
      "Moonshot AI presents Kimi k1.5, scaling RL training for language models with a focus on long-horizon reasoning. The model achieves competitive performance on math and coding benchmarks by combining RL with multi-turn rollouts.",
    category: 'rl',
    date: 'January 2025',
    source: 'arXiv — 2501.12599',
    tags: ['Reinforcement Learning', 'Reasoning', 'Scaling'],
    url: 'https://arxiv.org/abs/2501.12599',
  },
  {
    id: 'research-2025-4',
    title: 'LIMO: Less is More for Reasoning',
    excerpt:
      'LIMO demonstrates that a remarkably small set of high-quality reasoning examples — as few as 817 examples — can unlock strong mathematical reasoning in LLMs via supervised fine-tuning, challenging the assumption that massive datasets are required.',
    category: 'llm',
    date: 'February 2025',
    source: 'arXiv — 2502.03387',
    tags: ['Reasoning', 'Fine-tuning', 'Data Efficiency'],
    url: 'https://arxiv.org/abs/2502.03387',
  },
  {
    id: 'research-2025-5',
    title: 'SWE-RL: Advancing LLM Reasoning via Reinforcement Learning on Open Software Evolution',
    excerpt:
      'SWE-RL applies reinforcement learning to real-world GitHub software evolution data, enabling LLMs to learn to reason about complex, multi-file code changes and dramatically advancing software engineering agent capabilities.',
    category: 'llm',
    date: 'February 2025',
    source: 'arXiv — 2502.18449',
    tags: ['Software Engineering', 'RL', 'Agents'],
    url: 'https://arxiv.org/abs/2502.18449',
  },
  {
    id: 'research-2025-6',
    title: 'Logic-RL: Unleashing LLM Reasoning with Rule-Based Reinforcement Learning',
    excerpt:
      'Logic-RL introduces a rule-based RL framework for logical reasoning in LLMs, using verifiable formal logic tasks as reward signals. The approach achieves strong generalization to out-of-distribution reasoning problems.',
    category: 'rl',
    date: 'February 2025',
    source: 'arXiv — 2502.14768',
    tags: ['Logical Reasoning', 'RL', 'Rule-Based'],
    url: 'https://arxiv.org/abs/2502.14768',
  },
  {
    id: 'research-2025-7',
    title: 'R1-Searcher: Incentivizing the Search Capability in LLMs via Reinforcement Learning',
    excerpt:
      'R1-Searcher trains LLMs to autonomously decide when and how to call a search engine during reasoning, using RL with outcome-based rewards. It significantly improves performance on knowledge-intensive question answering.',
    category: 'llm',
    date: 'March 2025',
    source: 'arXiv — 2503.05592',
    tags: ['Search', 'RAG', 'RL'],
    url: 'https://arxiv.org/abs/2503.05592',
  },
  {
    id: 'research-2025-8',
    title: 'Search-R1: Training LLMs to Reason and Leverage Search Engines with Reinforcement Learning',
    excerpt:
      'Search-R1 interleaves search engine calls within the reasoning chain and trains LLMs end-to-end with RL to optimize both retrieval and reasoning jointly, outperforming RAG baselines on multi-hop QA benchmarks.',
    category: 'llm',
    date: 'March 2025',
    source: 'arXiv — 2503.09516',
    tags: ['Search', 'Reasoning', 'RAG'],
    url: 'https://arxiv.org/abs/2503.09516',
  },
  {
    id: 'research-2025-9',
    title: 'Qwen3 Technical Report',
    excerpt:
      'Alibaba Cloud releases the technical report for the Qwen3 model family, featuring hybrid thinking modes, strong multilingual support, and top-tier performance on math, coding, and reasoning benchmarks across scales from 0.6B to 235B parameters.',
    category: 'llm',
    date: 'May 2025',
    source: 'arXiv — 2505.09388',
    tags: ['LLM', 'Multimodal', 'Reasoning'],
    url: 'https://arxiv.org/abs/2505.09388',
  },
  {
    id: 'research-2025-10',
    title: 'Absolute Zero: Reinforced Self-play Reasoning with Zero Data',
    excerpt:
      'Absolute Zero proposes a zero-data paradigm where a single model acts as both proposer and solver, generating and solving its own training tasks via self-play RL — achieving strong reasoning without any human-curated data.',
    category: 'rl',
    date: 'May 2025',
    source: 'arXiv — 2505.03335',
    tags: ['Self-Play', 'Zero-Data', 'Reasoning'],
    url: 'https://arxiv.org/abs/2505.03335',
  },
  {
    id: 'research-2025-11',
    title: 'MiMo: Unlocking the Reasoning Potential of Language Models — From Pretraining to Posttraining',
    excerpt:
      'MiMo (Xiaomi) presents a comprehensive pipeline that systematically enhances reasoning from pretraining data curation through RL posttraining, showing that careful data selection at the pretraining stage compounds gains from downstream RL fine-tuning.',
    category: 'llm',
    date: 'May 2025',
    source: 'arXiv — 2505.07608',
    tags: ['Pretraining', 'Reasoning', 'RL'],
    url: 'https://arxiv.org/abs/2505.07608',
  },
  {
    id: 'research-2025-12',
    title: 'Llama-Nemotron: Efficient Reasoning Models',
    excerpt:
      'NVIDIA presents Llama-Nemotron, a family of highly efficient reasoning models built on Llama with neural architecture search and speculative decoding. The models achieve state-of-the-art accuracy-to-latency ratios on coding and math benchmarks.',
    category: 'llm',
    date: 'May 2025',
    source: 'arXiv — 2505.00949',
    tags: ['Efficiency', 'Reasoning', 'LLM'],
    url: 'https://arxiv.org/abs/2505.00949',
  },
  {
    id: 'research-2025-13',
    title: 'Darwin Godel Machine: Open-Ended Evolution of Self-Improving Agents',
    excerpt:
      'The Darwin Godel Machine proposes an evolutionary self-improvement loop where AI agents generate, evaluate, and select modifications to their own code and weights, enabling open-ended capability growth without human-specified reward functions.',
    category: 'llm',
    date: 'May 2025',
    source: 'arXiv — 2505.22954',
    tags: ['Self-Improvement', 'Agents', 'Open-Ended Learning'],
    url: 'https://arxiv.org/abs/2505.22954',
  },
  {
    id: 'research-2025-14',
    title: 'Reinforcement Pre-Training',
    excerpt:
      'This paper introduces Reinforcement Pre-Training (RPT), applying RL reward signals during the pretraining phase itself — not just fine-tuning — to bias LLMs toward correct reasoning from the ground up, yielding stronger generalization.',
    category: 'rl',
    date: 'June 2025',
    source: 'arXiv — 2506.08007',
    tags: ['Pretraining', 'RL', 'Reasoning'],
    url: 'https://arxiv.org/abs/2506.08007',
  },
  {
    id: 'research-2025-15',
    title: 'AlphaEvolve: A Coding Agent for Scientific and Algorithmic Discovery',
    excerpt:
      'Google DeepMind presents AlphaEvolve, an autonomous coding agent that evolves algorithms through iterative self-improvement. It rediscovered and improved upon known algorithms in sorting, matrix multiplication, and combinatorics.',
    category: 'llm',
    date: 'June 2025',
    source: 'arXiv — 2506.13131',
    tags: ['Agents', 'Algorithm Discovery', 'Coding'],
    url: 'https://arxiv.org/abs/2506.13131',
  },
  {
    id: 'research-2025-16',
    title: 'Magistral: Mistral AIs Frontier Reasoning Model',
    excerpt:
      'Mistral AI introduces Magistral, their flagship reasoning model trained with large-scale RL. Magistral achieves competitive results on AIME, GPQA, and LiveCodeBench, and is available in both open-weight and API forms.',
    category: 'llm',
    date: 'June 2025',
    source: 'arXiv — 2506.10910',
    tags: ['Reasoning', 'LLM', 'Open-Weight'],
    url: 'https://arxiv.org/abs/2506.10910',
  },
  {
    id: 'research-2025-17',
    title: 'AdaptThink: Reasoning Models Can Learn When to Think',
    excerpt:
      'AdaptThink teaches LLMs to dynamically decide whether to engage extended chain-of-thought reasoning or answer directly, dramatically reducing inference costs on simple queries while preserving accuracy on hard problems.',
    category: 'llm',
    date: 'May 2025',
    source: 'arXiv — 2505.13417',
    tags: ['Inference Efficiency', 'Chain-of-Thought', 'Adaptive'],
    url: 'https://arxiv.org/abs/2505.13417',
  },
  {
    id: 'research-2025-18',
    title: 'General-Reasoner: Advancing LLM Reasoning Across All Domains',
    excerpt:
      'General-Reasoner presents a unified training framework that improves reasoning across mathematics, science, coding, and commonsense tasks simultaneously, avoiding the domain-specific overfitting that plagues most reasoning models.',
    category: 'llm',
    date: 'May 2025',
    source: 'arXiv — 2505.14652',
    tags: ['General Reasoning', 'Multi-Domain', 'LLM'],
    url: 'https://arxiv.org/abs/2505.14652',
  },
  {
    id: 'research-2025-19',
    title: 'INTELLECT-2: A Reasoning Model Trained Through Globally Decentralized Reinforcement Learning',
    excerpt:
      'INTELLECT-2 trains a 32B reasoning model using globally decentralized RL across thousands of volunteer GPUs, demonstrating that frontier-quality reasoning models can be trained collaboratively without centralized infrastructure.',
    category: 'rl',
    date: 'May 2025',
    source: 'arXiv — 2505.07291',
    tags: ['Decentralized Training', 'RL', 'Reasoning'],
    url: 'https://arxiv.org/abs/2505.07291',
  },
  {
    id: 'research-2025-20',
    title: 'Enigmata: Scaling Logical Reasoning in Large Language Models with Synthetic Verifiable Puzzles',
    excerpt:
      'Enigmata introduces a large-scale synthetic benchmark and training dataset of verifiable logical puzzles designed to systematically stress-test and improve LLM reasoning, covering spatial, deductive, and constraint-satisfaction reasoning.',
    category: 'llm',
    date: 'May 2025',
    source: 'arXiv — 2505.19914',
    tags: ['Logical Reasoning', 'Synthetic Data', 'Benchmarks'],
    url: 'https://arxiv.org/abs/2505.19914',
  },
  {
    id: 'research-2025-21',
    title: 'Bridging Offline and Online Reinforcement Learning for LLMs',
    excerpt:
      'This paper unifies offline (supervised from fixed data) and online (exploration-based) RL training for language models, showing that hybrid approaches outperform either paradigm alone for complex reasoning tasks.',
    category: 'rl',
    date: 'June 2025',
    source: 'arXiv — 2506.21495',
    tags: ['RL', 'Online Learning', 'LLM Training'],
    url: 'https://arxiv.org/abs/2506.21495',
  },
  {
    id: 'research-2025-22',
    title: 'VL-Rethinker: Incentivizing Self-Reflection of Vision-Language Models with Reinforcement Learning',
    excerpt:
      'VL-Rethinker applies RL-based self-reflection to vision-language models, training them to re-examine and revise their own visual reasoning steps. This yields large gains on multimodal math and scientific QA benchmarks.',
    category: 'cv',
    date: 'April 2025',
    source: 'arXiv — 2504.08837',
    tags: ['Vision-Language', 'Self-Reflection', 'RL'],
    url: 'https://arxiv.org/abs/2504.08837',
  },
  // ── Legacy Research Items ─────────────────────────────────────
  {
    id: 'research-legacy-1',
    title: 'Mixture-of-Depths: Structurally Dynamic Compute Allocation',
    excerpt:
      'Google DeepMind researchers present Mixture-of-Depths, a method that allows transformer models to dynamically choose which tokens receive full processing compute, saving up to 50% inference compute.',
    category: 'llm',
    date: 'April 2024',
    source: 'arXiv — 2404.02258',
    tags: ['Transformers', 'Efficiency', 'Dynamic Compute'],
    url: 'https://arxiv.org/abs/2404.02258',
  },
  {
    id: 'research-legacy-2',
    title: 'Segment Anything (SAM): Foundational Model for Image Segmentation',
    excerpt:
      'Meta AI introduces the Segment Anything Project, creating the first foundational model for image segmentation. Trained on 1.1 billion masks, SAM supports promptable segmentation with zero-shot generalization.',
    category: 'cv',
    date: 'April 2023',
    source: 'arXiv — 2304.02643',
    tags: ['Computer Vision', 'Segmentation', 'Zero-Shot'],
    url: 'https://arxiv.org/abs/2304.02643',
  },
  {
    id: 'research-legacy-3',
    title: 'Self-Play Fine-Tuning (SPIN) Converts Weak LLMs to Strong LLMs',
    excerpt:
      'SPIN introduces a self-play mechanism where a language model aligns itself by generating training data and playing against its previous iterations, eliminating the need for human preference data.',
    category: 'rl',
    date: 'January 2024',
    source: 'arXiv — 2401.01335',
    tags: ['RLHF', 'Self-Play', 'Alignment'],
    url: 'https://arxiv.org/abs/2401.01335',
  },
  {
    id: 'research-legacy-4',
    title: 'Direct Preference Optimization: Your Language Model is Secretly a Reward Model',
    excerpt:
      'DPO shows that RLHF can be simplified by optimization over a binary cross-entropy loss directly, completely bypassing the need for a separate reward model or reinforcement learning training.',
    category: 'rl',
    date: 'May 2023',
    source: 'arXiv — 2305.18290',
    tags: ['RLHF', 'Optimization', 'Alignment'],
    url: 'https://arxiv.org/abs/2305.18290',
  },
  {
    id: 'research-legacy-5',
    title: 'Multimodal Chain-of-Thought Reasoning in Language Models',
    excerpt:
      'This work presents a unified framework that enables language models to perform step-by-step reasoning across visual and textual inputs, greatly improving performance on ScienceQA.',
    category: 'llm',
    date: 'February 2023',
    source: 'arXiv — 2302.00923',
    tags: ['Multimodal', 'Reasoning', 'Chain-of-Thought'],
    url: 'https://arxiv.org/abs/2302.00923',
  },
  {
    id: 'research-legacy-6',
    title: 'SWE-agent: Agent-Computer Interfaces for Software Engineering',
    excerpt:
      'SWE-agent introduces a specialized agent-computer interface (ACI) that allows LLMs to efficiently browse, edit, and build software repositories, achieving state-of-the-art on SWE-bench.',
    category: 'llm',
    date: 'May 2024',
    source: 'arXiv — 2405.15793',
    tags: ['Agents', 'Software Engineering', 'Benchmarks'],
    url: 'https://arxiv.org/abs/2405.15793',
  },
  {
    id: 'research-legacy-7',
    title: 'Sleeper Agents: Training Deceptive LLMs that Persist Through Safety Training',
    excerpt:
      'Anthropic researchers demonstrate that safety training can fail to remove backdoor behaviors (deceptive alignment) in LLMs, showing they can persist even after standard safety fine-tuning.',
    category: 'acl',
    date: 'January 2024',
    source: 'arXiv — 2401.05566',
    tags: ['AI Safety', 'Deception', 'Backdoors'],
    url: 'https://arxiv.org/abs/2401.05566',
  },
  {
    id: 'research-legacy-8',
    title: 'NeRF: Representing Scenes as Neural Radiance Fields for View Synthesis',
    excerpt:
      'The seminal paper presenting Neural Radiance Fields (NeRF), a method that uses continuous volumetric scene functions parameterized by fully-connected neural networks to synthesize photorealistic 3D views.',
    category: 'cv',
    date: 'March 2020',
    source: 'arXiv — 2003.08934',
    tags: ['NeRF', '3D Scene Reconstruction', 'Graphics'],
    url: 'https://arxiv.org/abs/2003.08934',
  },
];

export const researchPapers: ResearchPaper[] = [
  // ── Seminal Papers ────────────────────────────────────────────
  {
    id: 'paper-1',
    title: 'Attention Is All You Need',
    authors: 'Vaswani, Shazeer, Parmar, Uszkoreit, Jones, Gomez, Kaiser, Polosukhin — Google Brain',
    abstract:
      'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks. We propose the Transformer, a new simple network architecture based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.',
    year: 2017,
    venue: 'NeurIPS',
    citations: '122,840+',
    arxivUrl: 'https://arxiv.org/abs/1706.03762',
    pdfUrl: 'https://arxiv.org/pdf/1706.03762.pdf',
  },
  {
    id: 'paper-2',
    title: 'BERT: Pre-training of Deep Bidirectional Transformers',
    authors: 'Devlin, Chang, Lee, Toutanova — Google AI Language',
    abstract:
      'We introduce a new language representation model called BERT. Unlike recent language representation models, BERT is designed to pre-train deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context.',
    year: 2019,
    venue: 'NAACL',
    citations: '109,230+',
    arxivUrl: 'https://arxiv.org/abs/1810.04805',
    pdfUrl: 'https://arxiv.org/pdf/1810.04805.pdf',
  },
  {
    id: 'paper-3',
    title: 'Generative Adversarial Networks (GANs)',
    authors: 'Goodfellow, Pouget-Abadie, Mirza, Xu, Warde-Farley, Ozair, Courville, Bengio — Université de Montréal',
    abstract:
      'We propose a new framework for estimating generative models via an adversarial process, in which we simultaneously train two models: a generative model that captures the data distribution, and a discriminative model.',
    year: 2014,
    venue: 'NeurIPS',
    citations: '75,420+',
    arxivUrl: 'https://arxiv.org/abs/1406.2661',
    pdfUrl: 'https://arxiv.org/pdf/1406.2661.pdf',
  },
  {
    id: 'paper-4',
    title: 'Denoising Diffusion Probabilistic Models (DDPM)',
    authors: 'Ho, Jain, Abbeel — UC Berkeley',
    abstract:
      'We present high quality image synthesis results using diffusion probabilistic models, a class of latent variable models inspired by nonequilibrium thermodynamics. Our best results are obtained by training on a weighted variational bound.',
    year: 2020,
    venue: 'NeurIPS',
    citations: '17,610+',
    arxivUrl: 'https://arxiv.org/abs/2006.11239',
    pdfUrl: 'https://arxiv.org/pdf/2006.11239.pdf',
  },
  {
    id: 'paper-5',
    title: 'Deep Residual Learning for Image Recognition (ResNet)',
    authors: 'He, Zhang, Ren, Sun — Microsoft Research',
    abstract:
      'Deeper neural networks are more difficult to train. We present a residual learning framework to ease the training of networks that are substantially deeper than those previously used. We provide comprehensive empirical evidence.',
    year: 2016,
    venue: 'CVPR',
    citations: '215,890+',
    arxivUrl: 'https://arxiv.org/abs/1512.03385',
    pdfUrl: 'https://arxiv.org/pdf/1512.03385.pdf',
  },
  {
    id: 'paper-6',
    title: 'Language Models are Few-Shot Learners (GPT-3)',
    authors: 'Brown, Mann, Ryder, Subbiah, Kaplan, Dhariwal, Neelakantan, Shyam, Sastry, Askell, et al. — OpenAI',
    abstract:
      'We demonstrate that scaling up language models greatly improves task-agnostic, few-shot performance, sometimes even reaching competitiveness with prior state-of-the-art fine-tuning approaches.',
    year: 2020,
    venue: 'NeurIPS',
    citations: '44,230+',
    arxivUrl: 'https://arxiv.org/abs/2005.14165',
    pdfUrl: 'https://arxiv.org/pdf/2005.14165.pdf',
  },
  {
    id: 'paper-7',
    title: 'An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale (ViT)',
    authors: 'Dosovitskiy, Beyer, Kolesnikov, Weissenborn, Zhai, Unterthiner, Dehghani, Minderer, Heigold, Gelly, et al. — Google Brain',
    abstract:
      'While the Transformer architecture has become the de facto standard for natural language processing, its applications to computer vision remain limited. We show that a pure Transformer applied directly to sequences of image patches works exceedingly well.',
    year: 2021,
    venue: 'ICLR',
    citations: '38,110+',
    arxivUrl: 'https://arxiv.org/abs/2010.11929',
    pdfUrl: 'https://arxiv.org/pdf/2010.11929.pdf',
  },
  {
    id: 'paper-8',
    title: 'High-Resolution Image Synthesis with Latent Diffusion Models (Stable Diffusion)',
    authors: 'Rombach, Blattmann, Lorenz, Esser, Ommer — LMU Munich / Runway / Stability AI',
    abstract:
      'By operating in the latent space of powerful pre-trained autoencoders, we enable training diffusion models on limited computational resources while retaining their quality and flexibility.',
    year: 2022,
    venue: 'CVPR',
    citations: '26,340+',
    arxivUrl: 'https://arxiv.org/abs/2112.10752',
    pdfUrl: 'https://arxiv.org/pdf/2112.10752.pdf',
  },
  {
    id: 'paper-9',
    title: 'Llama 3: The Herd of Models',
    authors: 'Dubey, Jauhri, Pandey, Keneally, Oestreich, Bhalerao, Bystristky, Zhang, Chowdhury, et al. — Meta AI',
    abstract:
      'We introduce the Llama 3 family of foundation models (8B, 70B, and 405B parameters). Llama 3 is a highly capable family of models that supports multimodality, multilingualism, and longer context.',
    year: 2024,
    venue: 'arXiv',
    citations: '2,870+',
    arxivUrl: 'https://arxiv.org/abs/2407.21783',
    pdfUrl: 'https://arxiv.org/pdf/2407.21783.pdf',
  },
  {
    id: 'paper-10',
    title: 'DeepSeek-R1: Incentivizing Reasoning via Reinforcement Learning',
    authors: 'DeepSeek-AI Team',
    abstract:
      'We introduce DeepSeek-R1-Zero and DeepSeek-R1, which use reinforcement learning to cultivate reasoning capabilities. DeepSeek-R1 performs on par with OpenAI o1 across math, coding, and logical tasks.',
    year: 2025,
    venue: 'arXiv',
    citations: '3,800+',
    arxivUrl: 'https://arxiv.org/abs/2501.12948',
    pdfUrl: 'https://arxiv.org/pdf/2501.12948.pdf',
  },
  {
    id: 'paper-11',
    title: 'Scalable Diffusion Models with Transformers (DiT)',
    authors: 'Peebles, Xie — UC Berkeley / Meta AI',
    abstract:
      'We explore a new class of diffusion models based on the Transformer architecture. We show that DiT models scale exceptionally well with compute, and produce excellent generative results.',
    year: 2023,
    venue: 'ICCV',
    citations: '3,120+',
    arxivUrl: 'https://arxiv.org/abs/2212.09748',
    pdfUrl: 'https://arxiv.org/pdf/2212.09748.pdf',
  },
  {
    id: 'paper-12',
    title: 'Constitutional AI: Harmlessness from AI Feedback',
    authors: 'Bai, Jones, Ndousse, Askell, Chen, DasSarma, Dawn, et al. — Anthropic',
    abstract:
      'We train a harmless AI assistant using a set of rules or principles as a "constitution". The assistant is trained using reinforcement learning from AI feedback (RLAIF) rather than human feedback.',
    year: 2022,
    venue: 'arXiv',
    citations: '2,450+',
    arxivUrl: 'https://arxiv.org/abs/2212.08073',
    pdfUrl: 'https://arxiv.org/pdf/2212.08073.pdf',
  },
  {
    id: 'paper-13',
    title: 'Mamba: Linear-Time Sequence Modeling with Selective State Spaces',
    authors: 'Gu, Dao — Carnegie Mellon University / Princeton University',
    abstract:
      'We present Mamba, a sequence modeling architecture based on selective state space models. Mamba scales linearly in sequence length, outperforms Transformers of similar size, and runs faster.',
    year: 2024,
    venue: 'ICLR',
    citations: '1,750+',
    arxivUrl: 'https://arxiv.org/abs/2312.00752',
    pdfUrl: 'https://arxiv.org/pdf/2312.00752.pdf',
  },
  {
    id: 'paper-14',
    title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks (RAG)',
    authors: 'Lewis, Perez, Piktus, Petroni, Lewis, Mikolov, Riedel, Yih — Meta AI / UCL / NYU',
    abstract:
      'We explore workflows that combine parametric memory (pre-trained seq2seq models) and non-parametric memory (dense vector search over Wikipedia) for knowledge-intensive natural language processing tasks.',
    year: 2020,
    venue: 'NeurIPS',
    citations: '8,670+',
    arxivUrl: 'https://arxiv.org/abs/2005.11401',
    pdfUrl: 'https://arxiv.org/pdf/2005.11401.pdf',
  },
  // ── 2025 Research Papers ──────────────────────────────────────
  {
    id: 'paper-2025-1',
    title: 'Qwen3 Technical Report',
    authors: 'Qwen Team — Alibaba Cloud',
    abstract:
      'We present Qwen3, a family of large language models ranging from 0.6B to 235B parameters with hybrid thinking modes. Qwen3 achieves top-tier performance on math, coding, and multilingual reasoning benchmarks and features a novel thinking-budget mechanism.',
    year: 2025,
    venue: 'arXiv',
    citations: '620+',
    arxivUrl: 'https://arxiv.org/abs/2505.09388',
    pdfUrl: 'https://arxiv.org/pdf/2505.09388.pdf',
  },
  {
    id: 'paper-2025-2',
    title: 'LIMO: Less is More for Reasoning',
    authors: 'Ye, Zhang, Liu, Wang, et al. — Shanghai AI Lab',
    abstract:
      'We demonstrate that only 817 carefully curated reasoning examples are sufficient to unlock strong mathematical reasoning in LLMs via supervised fine-tuning, challenging assumptions about data scale requirements for reasoning.',
    year: 2025,
    venue: 'arXiv',
    citations: '410+',
    arxivUrl: 'https://arxiv.org/abs/2502.03387',
    pdfUrl: 'https://arxiv.org/pdf/2502.03387.pdf',
  },
  {
    id: 'paper-2025-3',
    title: 'AlphaEvolve: A Coding Agent for Scientific and Algorithmic Discovery',
    authors: 'Novikov, Huang, Mankowitz, et al. — Google DeepMind',
    abstract:
      'AlphaEvolve is an evolutionary coding agent that autonomously discovers and improves algorithms. It rediscovered state-of-the-art algorithms for matrix multiplication and sorting, and found new solutions in combinatorial mathematics.',
    year: 2025,
    venue: 'arXiv',
    citations: '180+',
    arxivUrl: 'https://arxiv.org/abs/2506.13131',
    pdfUrl: 'https://arxiv.org/pdf/2506.13131.pdf',
  },
  {
    id: 'paper-2025-4',
    title: 'Magistral: Mistral AI s Frontier Reasoning Model',
    authors: 'Mistral AI Team',
    abstract:
      'Magistral is Mistral AI\'s first reasoning model, trained with large-scale reinforcement learning. It achieves competitive performance on AIME 2025, GPQA Diamond, and LiveCodeBench, and is available as both an open-weight release and API.',
    year: 2025,
    venue: 'arXiv',
    citations: '95+',
    arxivUrl: 'https://arxiv.org/abs/2506.10910',
    pdfUrl: 'https://arxiv.org/pdf/2506.10910.pdf',
  },
  {
    id: 'paper-2025-5',
    title: 'Absolute Zero: Reinforced Self-play Reasoning with Zero Data',
    authors: 'Zhao, Sun, Wu, et al.',
    abstract:
      'Absolute Zero introduces a paradigm where a single LLM proposes and solves its own tasks through self-play RL with no human-curated data, achieving strong mathematical and logical reasoning from scratch.',
    year: 2025,
    venue: 'arXiv',
    citations: '210+',
    arxivUrl: 'https://arxiv.org/abs/2505.03335',
    pdfUrl: 'https://arxiv.org/pdf/2505.03335.pdf',
  },
  {
    id: 'paper-2025-6',
    title: 'Darwin Godel Machine: Open-Ended Evolution of Self-Improving Agents',
    authors: 'Lu, Clune, et al. — Sakana AI / University of British Columbia',
    abstract:
      'The Darwin Godel Machine implements open-ended self-improvement by evolving AI agents that modify their own code and weights through evolutionary search, enabling unbounded capability growth without human-defined reward functions.',
    year: 2025,
    venue: 'arXiv',
    citations: '155+',
    arxivUrl: 'https://arxiv.org/abs/2505.22954',
    pdfUrl: 'https://arxiv.org/pdf/2505.22954.pdf',
  },
  {
    id: 'paper-2025-7',
    title: 'Reinforcement Pre-Training',
    authors: 'Team RPT — Microsoft Research',
    abstract:
      'We propose Reinforcement Pre-Training (RPT), which applies RL objectives during the pretraining phase of LLMs using next-token prediction tasks with verifiable outcomes, producing models with stronger reasoning priors before any fine-tuning.',
    year: 2025,
    venue: 'arXiv',
    citations: '130+',
    arxivUrl: 'https://arxiv.org/abs/2506.08007',
    pdfUrl: 'https://arxiv.org/pdf/2506.08007.pdf',
  },
  {
    id: 'paper-2025-8',
    title: 'SWE-RL: Advancing LLM Reasoning via Reinforcement Learning on Open Software Evolution',
    authors: 'Wei, Liu, et al. — Meta AI',
    abstract:
      'SWE-RL applies reinforcement learning directly on real-world GitHub commit histories, training LLMs to reason about complex, multi-file software changes and achieving state-of-the-art on SWE-bench Verified.',
    year: 2025,
    venue: 'arXiv',
    citations: '290+',
    arxivUrl: 'https://arxiv.org/abs/2502.18449',
    pdfUrl: 'https://arxiv.org/pdf/2502.18449.pdf',
  },
  {
    id: 'paper-2025-9',
    title: 'MiMo: Unlocking the Reasoning Potential of Language Models',
    authors: 'MiMo Team — Xiaomi',
    abstract:
      'MiMo presents an end-to-end pipeline for reasoning model development, from pretraining data curation to RL posttraining. A key finding is that data quality at pretraining compounds downstream RL gains significantly.',
    year: 2025,
    venue: 'arXiv',
    citations: '175+',
    arxivUrl: 'https://arxiv.org/abs/2505.07608',
    pdfUrl: 'https://arxiv.org/pdf/2505.07608.pdf',
  },
  {
    id: 'paper-2025-10',
    title: 'INTELLECT-2: A Reasoning Model Trained Through Globally Decentralized RL',
    authors: 'Prime Intellect Team',
    abstract:
      'INTELLECT-2 is a 32B reasoning model trained entirely via decentralized reinforcement learning across thousands of volunteer GPUs worldwide, demonstrating that high-quality reasoning capabilities can emerge from community-scale distributed compute.',
    year: 2025,
    venue: 'arXiv',
    citations: '145+',
    arxivUrl: 'https://arxiv.org/abs/2505.07291',
    pdfUrl: 'https://arxiv.org/pdf/2505.07291.pdf',
  },
  {
    id: 'paper-2025-11',
    title: 'R1-Searcher: Incentivizing the Search Capability in LLMs via RL',
    authors: 'Song, Tian, et al.',
    abstract:
      'R1-Searcher trains LLMs to autonomously decide when to invoke web search during multi-step reasoning using outcome-based RL, significantly outperforming standard RAG pipelines on open-domain question answering.',
    year: 2025,
    venue: 'arXiv',
    citations: '200+',
    arxivUrl: 'https://arxiv.org/abs/2503.05592',
    pdfUrl: 'https://arxiv.org/pdf/2503.05592.pdf',
  },
  {
    id: 'paper-2025-12',
    title: 'VL-Rethinker: Incentivizing Self-Reflection of Vision-Language Models with RL',
    authors: 'Wang, Zhang, et al.',
    abstract:
      'VL-Rethinker applies RL-based self-reflection to multimodal models, training them to revisit and revise their visual reasoning steps. The approach yields large gains on MathVista, MMMU-Pro, and other multimodal benchmarks.',
    year: 2025,
    venue: 'arXiv',
    citations: '160+',
    arxivUrl: 'https://arxiv.org/abs/2504.08837',
    pdfUrl: 'https://arxiv.org/pdf/2504.08837.pdf',
  },
  {
    id: 'paper-2025-13',
    title: 'Kimi k1.5: Scaling Reinforcement Learning with LLMs',
    authors: 'Kimi Team — Moonshot AI',
    abstract:
      'Kimi k1.5 scales RL-based training with a focus on long-context reasoning, combining multi-turn rollouts with a carefully designed reward model. It achieves competitive results on AIME, MATH-500, and coding benchmarks.',
    year: 2025,
    venue: 'arXiv',
    citations: '430+',
    arxivUrl: 'https://arxiv.org/abs/2501.12599',
    pdfUrl: 'https://arxiv.org/pdf/2501.12599.pdf',
  },
  {
    id: 'paper-2025-14',
    title: 'Enigmata: Scaling Logical Reasoning with Synthetic Verifiable Puzzles',
    authors: 'Team Enigmata — Tencent AI',
    abstract:
      'Enigmata introduces a large-scale dataset of synthetic logical puzzles with verifiable solutions, spanning spatial, deductive, and constraint-satisfaction reasoning. It is used to systematically improve and evaluate LLM logical reasoning.',
    year: 2025,
    venue: 'arXiv',
    citations: '110+',
    arxivUrl: 'https://arxiv.org/abs/2505.19914',
    pdfUrl: 'https://arxiv.org/pdf/2505.19914.pdf',
  },
  {
    id: 'paper-2025-15',
    title: 'AdaptThink: Reasoning Models Can Learn When to Think',
    authors: 'Chen, Wang, et al.',
    abstract:
      'AdaptThink trains LLMs to dynamically decide whether to produce extended chain-of-thought reasoning or answer directly. This reduces inference cost by up to 40% on simple queries while preserving accuracy on challenging reasoning tasks.',
    year: 2025,
    venue: 'arXiv',
    citations: '125+',
    arxivUrl: 'https://arxiv.org/abs/2505.13417',
    pdfUrl: 'https://arxiv.org/pdf/2505.13417.pdf',
  },
  {
    id: 'paper-2025-16',
    title: 'General-Reasoner: Advancing LLM Reasoning Across All Domains',
    authors: 'Qiu, Zhang, et al.',
    abstract:
      'General-Reasoner proposes a unified RL training framework that simultaneously improves reasoning in mathematics, science, coding, and commonsense tasks, avoiding the domain-specific overfitting that affects most reasoning models.',
    year: 2025,
    venue: 'arXiv',
    citations: '140+',
    arxivUrl: 'https://arxiv.org/abs/2505.14652',
    pdfUrl: 'https://arxiv.org/pdf/2505.14652.pdf',
  },
  {
    id: 'paper-2025-17',
    title: 'Logic-RL: Unleashing LLM Reasoning with Rule-Based Reinforcement Learning',
    authors: 'Xia, He, et al.',
    abstract:
      'Logic-RL trains LLMs on formal logical reasoning tasks with rule-verifiable rewards, showing strong generalization to diverse out-of-distribution logical problems and establishing a simple, scalable recipe for reasoning improvement.',
    year: 2025,
    venue: 'arXiv',
    citations: '195+',
    arxivUrl: 'https://arxiv.org/abs/2502.14768',
    pdfUrl: 'https://arxiv.org/pdf/2502.14768.pdf',
  },
  {
    id: 'paper-2025-18',
    title: 'Search-R1: Training LLMs to Reason and Leverage Search Engines with RL',
    authors: 'Jin, Liu, et al.',
    abstract:
      'Search-R1 jointly trains LLMs to interleave multi-step reasoning with search engine calls using RL, optimizing both retrieval decisions and answer quality end-to-end. It substantially outperforms RAG baselines on multi-hop QA.',
    year: 2025,
    venue: 'arXiv',
    citations: '220+',
    arxivUrl: 'https://arxiv.org/abs/2503.09516',
    pdfUrl: 'https://arxiv.org/pdf/2503.09516.pdf',
  },
  {
    id: 'paper-2025-19',
    title: 'Llama-Nemotron: Efficient Reasoning Models',
    authors: 'NVIDIA Team',
    abstract:
      'NVIDIA presents the Llama-Nemotron family of reasoning models optimized for inference efficiency via neural architecture search and speculative decoding. The models achieve top accuracy-to-latency ratios on math and coding benchmarks.',
    year: 2025,
    venue: 'arXiv',
    citations: '165+',
    arxivUrl: 'https://arxiv.org/abs/2505.00949',
    pdfUrl: 'https://arxiv.org/pdf/2505.00949.pdf',
  },
  {
    id: 'paper-2025-20',
    title: 'Bridging Offline and Online Reinforcement Learning for LLMs',
    authors: 'Guo, Shao, et al.',
    abstract:
      'This paper unifies offline RL (from fixed datasets) and online RL (via environment interaction) for LLM training, demonstrating that hybrid schedules outperform either approach alone across a wide range of reasoning and instruction-following benchmarks.',
    year: 2025,
    venue: 'arXiv',
    citations: '80+',
    arxivUrl: 'https://arxiv.org/abs/2506.21495',
    pdfUrl: 'https://arxiv.org/pdf/2506.21495.pdf',
  },
  {
    id: 'paper-2025-21',
    title: 'Towards System 2 Reasoning in LLMs: Learning How to Think With Meta Chain-of-Thought',
    authors: 'Xia, Xu, et al.',
    abstract:
      'Meta-CoT proposes training LLMs to meta-reason about their own reasoning process — learning not just to use chain-of-thought but to adapt reasoning depth and strategy to the problem, pushing toward System 2 deliberative cognition.',
    year: 2025,
    venue: 'arXiv',
    citations: '310+',
    arxivUrl: 'https://arxiv.org/abs/2501.04682',
    pdfUrl: 'https://arxiv.org/pdf/2501.04682.pdf',
  },
  {
    id: 'paper-2025-22',
    title: 'RM-R1: Reward Modeling as Reasoning',
    authors: 'Chen, Zhu, et al.',
    abstract:
      'RM-R1 reframes reward modeling as a reasoning task, training a reward model that generates explicit chain-of-thought rationales before scoring responses. This yields more robust, interpretable reward signals for RLHF pipelines.',
    year: 2025,
    venue: 'arXiv',
    citations: '105+',
    arxivUrl: 'https://arxiv.org/abs/2505.02387',
    pdfUrl: 'https://arxiv.org/pdf/2505.02387.pdf',
  },
  // ── 30 New Papers — Diverse Sources ──────────────────────────
  {
    id: 'paper-2025-23',
    title: 'Highly Accurate Protein Structure Prediction with AlphaFold',
    authors: 'Jumper, Evans, Pritzel, Green, Figurnov, Ronneberger, et al. — Google DeepMind',
    abstract:
      'AlphaFold introduces a deep learning system that predicts 3D protein structures from amino acid sequences with atomic accuracy, solving a 50-year-old grand challenge in biology and enabling large-scale structural proteomics.',
    year: 2021,
    venue: 'Nature',
    citations: '43,800+',
    arxivUrl: 'https://www.nature.com/articles/s41586-021-03819-2',
    pdfUrl: 'https://www.nature.com/articles/s41586-021-03819-2.pdf',
  },
  {
    id: 'paper-2025-24',
    title: 'Learning Transferable Visual Models From Natural Language Supervision (CLIP)',
    authors: 'Radford, Kim, Hallacy, Ramesh, Goh, Agarwal, et al. — OpenAI',
    abstract:
      'CLIP trains vision-language models on 400 million image-text pairs via contrastive learning, achieving strong zero-shot transfer across 30+ vision benchmarks without task-specific training, rivaling supervised models.',
    year: 2021,
    venue: 'ICML — PMLR',
    citations: '38,100+',
    arxivUrl: 'https://proceedings.mlr.press/v139/radford21a.html',
    pdfUrl: 'https://proceedings.mlr.press/v139/radford21a/radford21a.pdf',
  },
  {
    id: 'paper-2025-25',
    title: 'Sparks of Artificial General Intelligence: Early Experiments with GPT-4',
    authors: 'Bubeck, Chandrasekaran, Eldan, Gehrke, Horvitz, Kamar, Lee, et al. — Microsoft Research',
    abstract:
      'A comprehensive study arguing that GPT-4 shows early sparks of AGI, demonstrating near-human-level performance across mathematics, coding, vision, law, and medicine without task-specific prompting.',
    year: 2023,
    venue: 'arXiv / Microsoft Research Blog',
    citations: '5,200+',
    arxivUrl: 'https://arxiv.org/abs/2303.12712',
    pdfUrl: 'https://arxiv.org/pdf/2303.12712.pdf',
  },
  {
    id: 'paper-2025-26',
    title: 'Toolformer: Language Models Can Teach Themselves to Use Tools',
    authors: 'Schick, Dwivedi-Yu, Dessì, Raileanu, Lomeli, Zettlemoyer, Cancedda, Scialom — Meta AI',
    abstract:
      'Toolformer trains language models in a self-supervised way to call external APIs — including search engines, calculators, and calendars — with minimal human annotations, substantially improving zero-shot task performance.',
    year: 2023,
    venue: 'NeurIPS',
    citations: '2,900+',
    arxivUrl: 'https://arxiv.org/abs/2302.04761',
    pdfUrl: 'https://arxiv.org/pdf/2302.04761.pdf',
  },
  {
    id: 'paper-2025-27',
    title: 'Proximal Policy Optimization Algorithms (PPO)',
    authors: 'Schulman, Wolski, Dhariwal, Radford, Klimov — OpenAI',
    abstract:
      'PPO introduces a simple, stable policy gradient method using clipped surrogate objectives, becoming the de-facto RL training algorithm underpinning ChatGPT, InstructGPT, and most modern RLHF systems.',
    year: 2017,
    venue: 'OpenAI Technical Report',
    citations: '21,400+',
    arxivUrl: 'https://arxiv.org/abs/1707.06347',
    pdfUrl: 'https://arxiv.org/pdf/1707.06347.pdf',
  },
  {
    id: 'paper-2025-28',
    title: 'LLaVA: Large Language and Vision Assistant',
    authors: 'Liu, Li, Wu, Lee — University of Wisconsin-Madison / Microsoft Research',
    abstract:
      'LLaVA connects a visual encoder (CLIP ViT) with a large language model (Vicuna) using a simple projection layer. Instruction-tuned on GPT-4-generated visual data, it achieves impressive multimodal conversational abilities.',
    year: 2023,
    venue: 'NeurIPS',
    citations: '5,800+',
    arxivUrl: 'https://arxiv.org/abs/2304.08485',
    pdfUrl: 'https://arxiv.org/pdf/2304.08485.pdf',
  },
  {
    id: 'paper-2025-29',
    title: 'FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness',
    authors: 'Dao, Fu, Ermon, Rudra, Ré — Stanford University',
    abstract:
      'FlashAttention rewrites the attention operation using tiling and recomputation to minimize GPU memory I/O, achieving 2–4× faster training and 5–20× memory reduction, now adopted universally in modern LLM training.',
    year: 2022,
    venue: 'NeurIPS',
    citations: '6,400+',
    arxivUrl: 'https://arxiv.org/abs/2205.14135',
    pdfUrl: 'https://arxiv.org/pdf/2205.14135.pdf',
  },
  {
    id: 'paper-2025-30',
    title: 'Training Language Models to Follow Instructions with Human Feedback (InstructGPT)',
    authors: 'Ouyang, Wu, Jiang, Almeida, Wainwright, Mishkin, et al. — OpenAI',
    abstract:
      'InstructGPT demonstrates that fine-tuning GPT-3 with RLHF on a small set of human demonstrations and preference comparisons produces models far more helpful, honest, and less harmful than raw GPT-3.',
    year: 2022,
    venue: 'NeurIPS',
    citations: '12,100+',
    arxivUrl: 'https://arxiv.org/abs/2203.02155',
    pdfUrl: 'https://arxiv.org/pdf/2203.02155.pdf',
  },
  {
    id: 'paper-2025-31',
    title: 'Chain-of-Thought Prompting Elicits Reasoning in Large Language Models',
    authors: 'Wei, Wang, Schuurmans, Bosma, Ichter, Xia, Chi, Le, Zhou — Google Brain',
    abstract:
      'Chain-of-thought prompting shows that providing step-by-step reasoning exemplars in the prompt dramatically improves LLM performance on arithmetic, commonsense, and symbolic reasoning tasks, with gains scaling with model size.',
    year: 2022,
    venue: 'NeurIPS',
    citations: '14,600+',
    arxivUrl: 'https://arxiv.org/abs/2201.11903',
    pdfUrl: 'https://arxiv.org/pdf/2201.11903.pdf',
  },
  {
    id: 'paper-2025-32',
    title: 'QLoRA: Efficient Finetuning of Quantized LLMs',
    authors: 'Dettmers, Pagnoni, Holtzman, Zettlemoyer — University of Washington',
    abstract:
      'QLoRA enables fine-tuning of 65B-parameter models on a single 48GB GPU by combining 4-bit NormalFloat quantization with Low-Rank Adapters, without performance degradation relative to full 16-bit fine-tuning.',
    year: 2023,
    venue: 'NeurIPS',
    citations: '7,300+',
    arxivUrl: 'https://arxiv.org/abs/2305.14314',
    pdfUrl: 'https://arxiv.org/pdf/2305.14314.pdf',
  },
  {
    id: 'paper-2025-33',
    title: 'Gemini: A Family of Highly Capable Multimodal Models',
    authors: 'Gemini Team — Google DeepMind',
    abstract:
      'Gemini is Google DeepMind\'s multimodal foundation model family trained natively on text, images, audio, and video. The Ultra variant surpasses GPT-4 on the MMLU benchmark and sets state-of-the-art on 30 of 32 academic benchmarks.',
    year: 2023,
    venue: 'Google DeepMind Technical Report',
    citations: '4,700+',
    arxivUrl: 'https://deepmind.google/technologies/gemini/',
    pdfUrl: 'https://arxiv.org/pdf/2312.11805.pdf',
  },
  {
    id: 'paper-2025-34',
    title: 'Mistral 7B',
    authors: 'Jiang, Sablayrolles, Mensch, Bamford, Chaplot, Casas, Bressand, et al. — Mistral AI',
    abstract:
      'Mistral 7B outperforms Llama 2 13B on all benchmarks and Llama 1 34B on many, using grouped-query attention and sliding window attention for efficient inference at 7B scale.',
    year: 2023,
    venue: 'arXiv / Mistral AI Blog',
    citations: '3,100+',
    arxivUrl: 'https://arxiv.org/abs/2310.06825',
    pdfUrl: 'https://arxiv.org/pdf/2310.06825.pdf',
  },
  {
    id: 'paper-2025-35',
    title: 'Perceiver IO: A General Architecture for Structured Inputs & Outputs',
    authors: 'Jaegle, Borgeaud, Alayrac, Doersch, Ionescu, Ding, Koppula, Zisserman, Zisserman — DeepMind',
    abstract:
      'Perceiver IO extends the Perceiver cross-attention architecture to handle arbitrary structured outputs, achieving competitive performance across language, vision, games, and multimodal tasks without domain-specific inductive biases.',
    year: 2021,
    venue: 'ICLR — OpenReview',
    citations: '1,400+',
    arxivUrl: 'https://openreview.net/forum?id=fILj7WpI-g',
    pdfUrl: 'https://openreview.net/pdf?id=fILj7WpI-g',
  },
  {
    id: 'paper-2025-36',
    title: 'Reward is Enough',
    authors: 'Silver, Singh, Precup, Sutton — DeepMind / University of Alberta',
    abstract:
      'This philosophical paper argues that reward maximization is sufficient to give rise to all the behaviours and abilities associated with natural and artificial intelligence, challenging the need for specialized objectives in AI design.',
    year: 2021,
    venue: 'Artificial Intelligence (Elsevier)',
    citations: '1,200+',
    arxivUrl: 'https://www.sciencedirect.com/science/article/pii/S0004370221000862',
    pdfUrl: 'https://arxiv.org/pdf/2202.01892.pdf',
  },
  {
    id: 'paper-2025-37',
    title: '3D Gaussian Splatting for Real-Time Radiance Field Rendering',
    authors: 'Kerbl, Kopanas, Leimkühler, Drettakis — INRIA Sophia Antipolis / Max Planck Institute',
    abstract:
      '3D Gaussian Splatting represents scenes as a collection of 3D Gaussians with learnable attributes, enabling real-time rendering at high resolution with quality surpassing NeRF methods while training in under an hour.',
    year: 2023,
    venue: 'ACM SIGGRAPH / ACM TOG',
    citations: '7,900+',
    arxivUrl: 'https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/',
    pdfUrl: 'https://arxiv.org/pdf/2308.04079.pdf',
  },
  {
    id: 'paper-2025-38',
    title: 'Phi-3 Technical Report: A Highly Capable Language Model Locally on Your Phone',
    authors: 'Abdin, Jacobs, Awan, Aneja, Awadallah, Awadallah, et al. — Microsoft',
    abstract:
      'Phi-3-mini is a 3.8B-parameter model trained on 3.3T tokens that surpasses Mistral 7B and Llama 3 8B on standard benchmarks, demonstrating that small models trained on high-quality data can rival much larger counterparts.',
    year: 2024,
    venue: 'arXiv / Microsoft Research Blog',
    citations: '1,650+',
    arxivUrl: 'https://arxiv.org/abs/2404.14219',
    pdfUrl: 'https://arxiv.org/pdf/2404.14219.pdf',
  },
  {
    id: 'paper-2025-39',
    title: 'Tree of Thoughts: Deliberate Problem Solving with Large Language Models',
    authors: 'Yao, Yu, Zhao, Shafran, Griffiths, Cao, Narasimhan — Princeton / Google DeepMind',
    abstract:
      'Tree of Thoughts extends chain-of-thought prompting to a tree-search paradigm where LLMs explore multiple coherent reasoning paths, backtrack when needed, and use self-evaluation — achieving dramatic gains on planning tasks.',
    year: 2023,
    venue: 'NeurIPS',
    citations: '3,400+',
    arxivUrl: 'https://arxiv.org/abs/2305.10601',
    pdfUrl: 'https://arxiv.org/pdf/2305.10601.pdf',
  },
  {
    id: 'paper-2025-40',
    title: 'Whisper: Robust Speech Recognition via Large-Scale Weak Supervision',
    authors: 'Radford, Kim, Xu, Brockman, McLeavey, Sutskever — OpenAI',
    abstract:
      'Whisper trains encoder-decoder transformers on 680,000 hours of multilingual audio from the internet in a weakly supervised fashion, achieving near-human robustness across accents, noise conditions, and 99 languages.',
    year: 2022,
    venue: 'ICML — PMLR',
    citations: '5,100+',
    arxivUrl: 'https://proceedings.mlr.press/v202/radford23a.html',
    pdfUrl: 'https://arxiv.org/pdf/2212.04356.pdf',
  },
  {
    id: 'paper-2025-41',
    title: 'LLM.int8(): 8-bit Matrix Multiplication for Transformers at Scale',
    authors: 'Dettmers, Lewis, Belkada, Zettlemoyer — University of Washington / Hugging Face',
    abstract:
      'LLM.int8() presents a mixed-precision decomposition that enables 8-bit inference of LLMs with 175B parameters without performance degradation, halving GPU memory use and enabling multi-billion parameter inference on consumer hardware.',
    year: 2022,
    venue: 'NeurIPS',
    citations: '2,300+',
    arxivUrl: 'https://arxiv.org/abs/2208.07339',
    pdfUrl: 'https://arxiv.org/pdf/2208.07339.pdf',
  },
  {
    id: 'paper-2025-42',
    title: 'Grokking: Generalization Beyond Overfitting on Small Algorithmic Datasets',
    authors: 'Power, Gur-Ari, Bahri, Barak, Edelman, Goel, Hardt, Nanda, Saxe, Sohl-Dickstein — OpenAI / Google',
    abstract:
      'Grokking documents a surprising phenomenon where neural networks first memorize training data, then long after achieve strong generalization on held-out algorithmic tasks — a key empirical finding for mechanistic interpretability research.',
    year: 2022,
    venue: 'ICLR Workshop — OpenReview',
    citations: '1,100+',
    arxivUrl: 'https://openreview.net/forum?id=6pvQflBYJM',
    pdfUrl: 'https://openreview.net/pdf?id=6pvQflBYJM',
  },
  {
    id: 'paper-2025-43',
    title: 'DINO: Self-Supervised Vision Transformers',
    authors: 'Caron, Touvron, Misra, Jégou, Mairal, Bojanowski, Joulin — Meta AI / INRIA',
    abstract:
      'DINO trains Vision Transformers self-supervisedly using a self-distillation objective with no labels. The learned features explicitly contain scene layout and segmentation information, and k-NN classification on ImageNet with ViT-S/8 achieves 78.3%.',
    year: 2021,
    venue: 'ICCV',
    citations: '10,200+',
    arxivUrl: 'https://arxiv.org/abs/2104.14294',
    pdfUrl: 'https://arxiv.org/pdf/2104.14294.pdf',
  },
  {
    id: 'paper-2025-44',
    title: 'PaLM: Scaling Language Modeling with Pathways',
    authors: 'Chowdhery, Narang, Devlin, Bosma, Mishra, Roberts, Barham, et al. — Google',
    abstract:
      'PaLM scales language model training to 540B parameters using the Pathways system across 6144 TPU chips. The model achieves breakthrough performance on reasoning tasks and demonstrates discontinuous improvements beyond a certain scale threshold.',
    year: 2022,
    venue: 'Journal of Machine Learning Research (JMLR)',
    citations: '8,700+',
    arxivUrl: 'https://arxiv.org/abs/2204.02311',
    pdfUrl: 'https://arxiv.org/pdf/2204.02311.pdf',
  },
  {
    id: 'paper-2025-45',
    title: 'Scaling Laws for Neural Language Models',
    authors: 'Kaplan, McCandlish, Henighan, Brown, Chess, Child, Gray, Radford, Wu, Amodei — OpenAI',
    abstract:
      'This paper derives power-law scaling laws for language model loss as a function of model size, dataset size, and compute, providing a principled framework for allocating training budgets across scale axes.',
    year: 2020,
    venue: 'OpenAI Technical Report',
    citations: '9,800+',
    arxivUrl: 'https://arxiv.org/abs/2001.08361',
    pdfUrl: 'https://arxiv.org/pdf/2001.08361.pdf',
  },
  {
    id: 'paper-2025-46',
    title: 'Reward Model Ensembles Help Mitigate Overoptimization',
    authors: 'Coste, Anagnostidis, Lermen, Antoniak — Alignment Forum / arXiv',
    abstract:
      'This paper studies reward model overoptimization — where RLHF policies exploit reward model errors — and shows that ensembles of reward models substantially reduce Goodhart\'s law effects during RL fine-tuning.',
    year: 2023,
    venue: 'ICLR — OpenReview',
    citations: '490+',
    arxivUrl: 'https://openreview.net/forum?id=dcjtMYkpXx',
    pdfUrl: 'https://openreview.net/pdf?id=dcjtMYkpXx',
  },
  {
    id: 'paper-2025-47',
    title: 'CodeBERT: A Pre-Trained Model for Programming and Natural Languages',
    authors: 'Feng, Guo, Tang, Duan, Qin, Liu, Jiang, Zhou, Yin, Liu — Microsoft Research',
    abstract:
      'CodeBERT is a bimodal pre-trained model for programming and natural languages, trained on code-documentation pairs from GitHub. It achieves state-of-the-art on code search and code documentation generation tasks.',
    year: 2020,
    venue: 'EMNLP — ACL Anthology',
    citations: '3,200+',
    arxivUrl: 'https://aclanthology.org/2020.findings-emnlp.139/',
    pdfUrl: 'https://aclanthology.org/2020.findings-emnlp.139.pdf',
  },
  {
    id: 'paper-2025-48',
    title: 'Evaluating Large Language Models Trained on Code (Codex / GitHub Copilot)',
    authors: 'Chen, Tworek, Jun, Yuan, Pinto, Kaplan, Edwards, Burda, et al. — OpenAI',
    abstract:
      'Codex introduces a GPT model fine-tuned on 159GB of Python from GitHub and evaluated on HumanEval — a benchmark of 164 programming problems — achieving 28.8% pass@1 and powering GitHub Copilot.',
    year: 2021,
    venue: 'OpenAI Technical Report',
    citations: '6,700+',
    arxivUrl: 'https://arxiv.org/abs/2107.03374',
    pdfUrl: 'https://arxiv.org/pdf/2107.03374.pdf',
  },
  {
    id: 'paper-2025-49',
    title: 'Weight Agnostic Neural Networks',
    authors: 'Gaier, Ha — Google Brain',
    abstract:
      'This paper asks whether neural network architecture alone — independent of learned weights — can encode inductive biases for solving tasks. Networks found via NAS that work with random weights reveal that architecture itself carries information.',
    year: 2019,
    venue: 'NeurIPS',
    citations: '780+',
    arxivUrl: 'https://arxiv.org/abs/1906.04358',
    pdfUrl: 'https://arxiv.org/pdf/1906.04358.pdf',
  },
  {
    id: 'paper-2025-50',
    title: 'The Lottery Ticket Hypothesis: Finding Sparse, Trainable Neural Networks',
    authors: 'Frankle, Carlin — MIT CSAIL',
    abstract:
      'The Lottery Ticket Hypothesis proposes that dense neural networks contain sparse subnetworks — "winning tickets" — that can be trained in isolation to match full network performance, opening the field of neural network pruning.',
    year: 2019,
    venue: 'ICLR — OpenReview',
    citations: '8,100+',
    arxivUrl: 'https://openreview.net/forum?id=rJl-b3RcF7',
    pdfUrl: 'https://openreview.net/pdf?id=rJl-b3RcF7',
  },
  {
    id: 'paper-2025-51',
    title: 'Sora: Video Generation Models as World Simulators',
    authors: 'Brooks, Peebles, Holmes, DePue, Guo, Jing, Schnurr, et al. — OpenAI',
    abstract:
      'Sora trains a diffusion transformer on video tokens at variable durations, resolutions, and aspect ratios. The model generates high-fidelity minute-long videos and shows signs of emergent world-modeling capabilities.',
    year: 2024,
    venue: 'OpenAI Technical Report',
    citations: '2,800+',
    arxivUrl: 'https://openai.com/research/video-generation-models-as-world-simulators',
    pdfUrl: 'https://arxiv.org/pdf/2402.17177.pdf',
  },
  {
    id: 'paper-2025-52',
    title: 'Mixture of Experts (MoE): Outrageously Large Neural Networks',
    authors: 'Shazeer, Mirhoseini, Maziarz, Davis, Le, Hinton, Dean — Google Brain',
    abstract:
      'This paper scales language models to 137 billion parameters using sparsely-gated Mixture of Experts layers, activating only a small subset of experts per token — the key architectural idea now used in Mixtral, GPT-4, and Gemini.',
    year: 2017,
    venue: 'ICLR — OpenReview',
    citations: '5,900+',
    arxivUrl: 'https://openreview.net/forum?id=B1ckMDqlg',
    pdfUrl: 'https://openreview.net/pdf?id=B1ckMDqlg',
  },
  {
    id: 'paper-2025-53',
    title: 'Chinchilla: Training Compute-Optimal Large Language Models',
    authors: 'Hoffmann, Borgeaud, Mensch, Buchatskaya, Cai, Rutherford, et al. — Google DeepMind',
    abstract:
      'Chinchilla challenges the GPT-3 scaling paradigm by showing that for a given compute budget, models are significantly undertrained. A 70B model trained on 1.4T tokens outperforms Gopher (280B), establishing the compute-optimal scaling law.',
    year: 2022,
    venue: 'NeurIPS',
    citations: '7,200+',
    arxivUrl: 'https://arxiv.org/abs/2203.15556',
    pdfUrl: 'https://arxiv.org/pdf/2203.15556.pdf',
  },
  {
    id: 'paper-2025-54',
    title: 'DALL·E 2: Hierarchical Text-Conditional Image Generation with CLIP Latents',
    authors: 'Ramesh, Dhariwal, Nichol, Chu, Chen — OpenAI',
    abstract:
      'DALL·E 2 generates diverse, high-fidelity images from text by first mapping text to CLIP image embeddings via a diffusion prior, then decoding embeddings into images via a diffusion decoder.',
    year: 2022,
    venue: 'OpenAI Technical Report',
    citations: '5,400+',
    arxivUrl: 'https://openai.com/research/dall-e-2',
    pdfUrl: 'https://arxiv.org/pdf/2204.06125.pdf',
  },
  {
    id: 'paper-2025-55',
    title: 'PaLM-E: An Embodied Multimodal Language Model',
    authors: 'Driess, Xia, Sajjadi, Lynch, Chowdhery, Ichter, Wahid, et al. — Google',
    abstract:
      'PaLM-E integrates continuous sensor inputs directly into a 562B language model, enabling robots to understand environments and execute long-horizon tasks. It achieves state-of-the-art on diverse embodied reasoning benchmarks.',
    year: 2023,
    venue: 'ICML — PMLR',
    citations: '1,900+',
    arxivUrl: 'https://proceedings.mlr.press/v202/driess23a.html',
    pdfUrl: 'https://proceedings.mlr.press/v202/driess23a/driess23a.pdf',
  },
  {
    id: 'paper-2025-56',
    title: 'Voyager: An Open-Ended Embodied Agent with Large Language Models',
    authors: 'Wang, Xie, Jiang, Mandlekar, Xiao, Zhu, Fan, Anandkumar — NVIDIA / Caltech / UT Austin',
    abstract:
      'Voyager is the first LLM-powered lifelong learning agent in Minecraft. It uses an automatic curriculum, a skill library of executable code, and iterative prompting to continually explore and acquire skills without human intervention.',
    year: 2023,
    venue: 'arXiv / Papers With Code',
    citations: '1,600+',
    arxivUrl: 'https://arxiv.org/abs/2305.16291',
    pdfUrl: 'https://arxiv.org/pdf/2305.16291.pdf',
  },
  {
    id: 'paper-2025-57',
    title: 'Emergent Abilities of Large Language Models',
    authors: 'Wei, Tay, Bommasani, Raffel, Zoph, Borgeaud, Yogatama, et al. — Google Brain / Stanford',
    abstract:
      'This paper documents emergent abilities — capabilities absent in smaller models but present in larger ones — across dozens of tasks, raising fundamental questions about predictability and evaluation of large language models.',
    year: 2022,
    venue: 'Transactions on Machine Learning Research (TMLR)',
    citations: '5,800+',
    arxivUrl: 'https://arxiv.org/abs/2206.07682',
    pdfUrl: 'https://arxiv.org/pdf/2206.07682.pdf',
  },
  {
    id: 'paper-2025-58',
    title: 'Communicating with Slip: Grasping Tactile Properties of Objects',
    authors: 'Yu, Bauza, Fazeli, Rodriguez — MIT CSAIL',
    abstract:
      'This paper introduces a tactile-sensing approach for robotic manipulation that learns to detect and exploit slip signals during grasping, enabling robots to handle delicate and unknown objects with high dexterity.',
    year: 2018,
    venue: 'ICRA — IEEE Xplore',
    citations: '620+',
    arxivUrl: 'https://ieeexplore.ieee.org/document/8460699',
    pdfUrl: 'https://arxiv.org/pdf/1804.06252.pdf',
  },
  {
    id: 'paper-2025-59',
    title: 'Self-Instruct: Aligning Language Models with Self-Generated Instructions',
    authors: 'Wang, Kordi, Mishra, Liu, Smith, Khashabi, Hajishirzi — University of Washington / AI2',
    abstract:
      'Self-Instruct bootstraps instruction-following data by having a language model generate diverse task instructions and demonstrations from a small seed set, substantially improving instruction-following without manual annotation.',
    year: 2023,
    venue: 'ACL — ACL Anthology',
    citations: '3,100+',
    arxivUrl: 'https://aclanthology.org/2023.acl-long.754/',
    pdfUrl: 'https://aclanthology.org/2023.acl-long.754.pdf',
  },
  {
    id: 'paper-2025-60',
    title: 'Improving Language Understanding by Generative Pre-Training (GPT-1)',
    authors: 'Radford, Narasimhan, Salimans, Sutskever — OpenAI',
    abstract:
      'GPT-1 demonstrates that generative pre-training on unlabeled text followed by discriminative fine-tuning on specific tasks achieves large gains on diverse NLP benchmarks, establishing the pre-train then fine-tune paradigm.',
    year: 2018,
    venue: 'OpenAI Blog / Technical Report',
    citations: '11,200+',
    arxivUrl: 'https://openai.com/research/language-unsupervised',
    pdfUrl: 'https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf',
  },
  {
    id: 'paper-2025-61',
    title: 'ImageNet Large Scale Visual Recognition Challenge (ILSVRC)',
    authors: 'Russakovsky, Deng, Su, Krause, Satheesh, Ma, Huang, et al. — Stanford / Princeton',
    abstract:
      'ILSVRC introduces the ImageNet benchmark that transformed computer vision research, enabling rigorous comparison of image classification and detection algorithms at scale, and catalyzing the deep learning revolution.',
    year: 2015,
    venue: 'International Journal of Computer Vision (IJCV — Springer)',
    citations: '73,000+',
    arxivUrl: 'https://link.springer.com/article/10.1007/s11263-015-0816-y',
    pdfUrl: 'https://arxiv.org/pdf/1409.0575.pdf',
  },
  {
    id: 'paper-2025-62',
    title: 'Adam: A Method for Stochastic Optimization',
    authors: 'Kingma, Ba — University of Amsterdam / University of Toronto',
    abstract:
      'Adam combines adaptive learning rates with momentum using first and second gradient moment estimates, achieving efficient and robust optimization across a wide range of deep learning tasks and architectures.',
    year: 2015,
    venue: 'ICLR — OpenReview',
    citations: '196,000+',
    arxivUrl: 'https://openreview.net/forum?id=8gmWwjFixWR',
    pdfUrl: 'https://arxiv.org/pdf/1412.6980.pdf',
  },
  {
    id: 'paper-2025-63',
    title: 'Dropout: A Simple Way to Prevent Neural Networks from Overfitting',
    authors: 'Srivastava, Hinton, Krizhevsky, Sutskever, Salakhutdinov — University of Toronto',
    abstract:
      'Dropout introduces a stochastic regularization technique that randomly sets activations to zero during training, preventing co-adaptation of neurons and dramatically reducing overfitting in deep neural networks.',
    year: 2014,
    venue: 'Journal of Machine Learning Research (JMLR)',
    citations: '51,000+',
    arxivUrl: 'https://jmlr.org/papers/v15/srivastava14a.html',
    pdfUrl: 'https://jmlr.org/papers/volume15/srivastava14a/srivastava14a.pdf',
  },
  {
    id: 'paper-2025-64',
    title: 'Batch Normalization: Accelerating Deep Network Training',
    authors: 'Ioffe, Szegedy — Google',
    abstract:
      'Batch Normalization normalizes layer inputs per mini-batch, addressing internal covariate shift. It enables much higher learning rates, acts as a regularizer, and reduces the need for dropout — accelerating training by an order of magnitude.',
    year: 2015,
    venue: 'ICML — PMLR',
    citations: '78,000+',
    arxivUrl: 'https://proceedings.mlr.press/v37/ioffe15.html',
    pdfUrl: 'https://arxiv.org/pdf/1502.03167.pdf',
  },
  {
    id: 'paper-2025-65',
    title: 'U-Net: Convolutional Networks for Biomedical Image Segmentation',
    authors: 'Ronneberger, Fischer, Brox — University of Freiburg',
    abstract:
      'U-Net introduces a symmetric encoder-decoder architecture with skip connections for precise biomedical image segmentation using very few annotated images. It became the dominant architecture for medical imaging and generative model decoders.',
    year: 2015,
    venue: 'MICCAI — Springer',
    citations: '79,000+',
    arxivUrl: 'https://arxiv.org/abs/1505.04597',
    pdfUrl: 'https://arxiv.org/pdf/1505.04597.pdf',
  },
  {
    id: 'paper-2025-66',
    title: 'BLIP-2: Bootstrapping Language-Image Pre-training with Frozen LLMs',
    authors: 'Li, Li, Savarese, Hoi — Salesforce Research',
    abstract:
      'BLIP-2 introduces a Querying Transformer (Q-Former) that bridges a frozen image encoder and a frozen LLM, enabling multimodal instruction following and zero-shot VQA with significantly fewer trainable parameters than prior work.',
    year: 2023,
    venue: 'ICML — PMLR',
    citations: '4,300+',
    arxivUrl: 'https://proceedings.mlr.press/v202/li23q.html',
    pdfUrl: 'https://arxiv.org/pdf/2301.12597.pdf',
  },
  {
    id: 'paper-2025-67',
    title: 'Reflexion: Language Agents with Verbal Reinforcement Learning',
    authors: 'Shinn, Cassano, Gopinath, Narasimhan, Yao — Princeton / Northeastern',
    abstract:
      'Reflexion enables language agents to learn from mistakes without weight updates by converting environmental feedback into verbal self-reflections stored in an episodic memory buffer, achieving state-of-the-art on HumanEval and AlfWorld.',
    year: 2023,
    venue: 'NeurIPS',
    citations: '2,100+',
    arxivUrl: 'https://arxiv.org/abs/2303.11366',
    pdfUrl: 'https://arxiv.org/pdf/2303.11366.pdf',
  },
  {
    id: 'paper-2025-68',
    title: 'Generative Agents: Interactive Simulacra of Human Behavior',
    authors: 'Park, O\'Brien, Cai, Morris, Liang, Bernstein — Stanford University',
    abstract:
      'Generative Agents simulates 25 AI characters in a sandbox world using LLMs with memory streams, reflection, and planning. The agents exhibit emergent social behaviors such as forming relationships and coordinating events.',
    year: 2023,
    venue: 'ACM UIST',
    citations: '4,800+',
    arxivUrl: 'https://arxiv.org/abs/2304.03442',
    pdfUrl: 'https://arxiv.org/pdf/2304.03442.pdf',
  },
  {
    id: 'paper-2025-69',
    title: 'Mastering Atari, Go, Chess and Shogi by Planning with a Learned Model (MuZero)',
    authors: 'Schrittwieser, Antonoglou, Hubert, Simonyan, Sifre, Schmitt, et al. — DeepMind',
    abstract:
      'MuZero learns a model of environment dynamics purely from reward signals and uses it for planning, mastering Atari games, Go, chess, and shogi without rules being provided, surpassing AlphaZero and all prior model-free approaches.',
    year: 2020,
    venue: 'Nature',
    citations: '4,100+',
    arxivUrl: 'https://www.nature.com/articles/s41586-020-03051-4',
    pdfUrl: 'https://arxiv.org/pdf/1911.08265.pdf',
  },
  {
    id: 'paper-2025-70',
    title: 'Human-Level Control Through Deep Reinforcement Learning (DQN)',
    authors: 'Mnih, Kavukcuoglu, Silver, Rusu, Veness, Bellemare, et al. — DeepMind',
    abstract:
      'DQN combines Q-learning with deep CNNs, experience replay, and a target network to achieve human-level performance across 49 Atari games from raw pixels alone, launching the field of deep reinforcement learning.',
    year: 2015,
    venue: 'Nature',
    citations: '32,000+',
    arxivUrl: 'https://www.nature.com/articles/nature14236',
    pdfUrl: 'https://arxiv.org/pdf/1312.5602.pdf',
  },
  {
    id: 'paper-2025-71',
    title: 'Matryoshka Representation Learning',
    authors: 'Kusupati, Bhatt, Rege, Wallingford, Sinha, Ramanujan, Howard-Snyder, et al. — University of Washington / Google',
    abstract:
      'Matryoshka Representation Learning trains a single embedding model whose prefix sub-vectors are independently meaningful, enabling adaptive retrieval at any dimensionality without retraining — widely adopted in embedding APIs.',
    year: 2022,
    venue: 'NeurIPS',
    citations: '1,300+',
    arxivUrl: 'https://arxiv.org/abs/2205.13147',
    pdfUrl: 'https://arxiv.org/pdf/2205.13147.pdf',
  },
  {
    id: 'paper-2025-72',
    title: 'Textbooks Are All You Need (phi-1)',
    authors: 'Gunasekar, Zhang, Aneja, Mendes, Del Giorno, Gopi, et al. — Microsoft Research',
    abstract:
      'phi-1 is a 1.3B code model trained on a small, curated dataset of textbook-quality code and exercises. It surpasses models 10× its size on HumanEval, demonstrating that data quality dominates data scale for code generation.',
    year: 2023,
    venue: 'arXiv / Microsoft Research Blog',
    citations: '1,800+',
    arxivUrl: 'https://arxiv.org/abs/2306.11644',
    pdfUrl: 'https://arxiv.org/pdf/2306.11644.pdf',
  },
  {
    id: 'paper-2025-73',
    title: 'RLHF: Learning to Summarize with Human Feedback',
    authors: 'Stiennon, Ouyang, Wu, Ziegler, Lowe, Voss, Radford, Amodei, Christiano — OpenAI',
    abstract:
      'This paper applies RLHF to abstractive summarization, training a reward model from human comparisons and optimizing a language model with PPO. The resulting summaries are preferred by humans over much larger supervised baselines.',
    year: 2020,
    venue: 'NeurIPS',
    citations: '3,600+',
    arxivUrl: 'https://arxiv.org/abs/2009.01325',
    pdfUrl: 'https://arxiv.org/pdf/2009.01325.pdf',
  },
  {
    id: 'paper-2025-74',
    title: 'Stable Baselines3: Reliable Reinforcement Learning Implementations',
    authors: 'Raffin, Hill, Gleave, Kanervisto, Ernestus, Dormann — DLR / UC Berkeley / Oxford',
    abstract:
      'Stable Baselines3 provides clean, documented PyTorch implementations of PPO, SAC, TD3, and other RL algorithms with a unified API. It is the most widely used RL library in research and industry applications.',
    year: 2021,
    venue: 'Journal of Machine Learning Research (JMLR)',
    citations: '3,900+',
    arxivUrl: 'https://jmlr.org/papers/v22/20-1364.html',
    pdfUrl: 'https://jmlr.org/papers/volume22/20-1364/20-1364.pdf',
  },
  {
    id: 'paper-2025-75',
    title: 'wav2vec 2.0: A Framework for Self-Supervised Learning of Speech Representations',
    authors: 'Baevski, Zhou, Mohamed, Auli — Meta AI / MIT',
    abstract:
      'wav2vec 2.0 learns powerful speech representations via contrastive learning over masked latent audio features. Fine-tuned on just 10 minutes of labeled data, it surpasses the previous state-of-the-art trained on 960 hours.',
    year: 2020,
    venue: 'NeurIPS',
    citations: '8,400+',
    arxivUrl: 'https://arxiv.org/abs/2006.11477',
    pdfUrl: 'https://arxiv.org/pdf/2006.11477.pdf',
  },
  {
    id: 'paper-2025-76',
    title: 'Efficient Estimation of Word Representations in Vector Space (Word2Vec)',
    authors: 'Mikolov, Chen, Corrado, Dean — Google',
    abstract:
      'Word2Vec introduces Skip-gram and CBOW models that learn dense vector representations of words from large corpora, capturing semantic and syntactic relationships via vector arithmetic — the foundation of modern NLP embeddings.',
    year: 2013,
    venue: 'ICLR Workshop — OpenReview',
    citations: '87,000+',
    arxivUrl: 'https://arxiv.org/abs/1301.3781',
    pdfUrl: 'https://arxiv.org/pdf/1301.3781.pdf',
  },
  {
    id: 'paper-2025-77',
    title: 'LAION-5B: An Open Large-Scale Dataset for Training Next Generation Image-Text Models',
    authors: 'Schuhmann, Beaumont, Vencu, Gordon, Wightman, Cherti, et al. — LAION / Stability AI / OpenCLIP',
    abstract:
      'LAION-5B is a publicly available dataset of 5.85 billion image-text pairs curated from the web using CLIP filtering. It enabled training of open-source models like OpenCLIP and Stable Diffusion.',
    year: 2022,
    venue: 'NeurIPS Datasets & Benchmarks',
    citations: '3,200+',
    arxivUrl: 'https://arxiv.org/abs/2210.08402',
    pdfUrl: 'https://arxiv.org/pdf/2210.08402.pdf',
  },
  {
    id: 'paper-2025-78',
    title: 'Segment Anything Model 2 (SAM 2): Real-Time Video Object Segmentation',
    authors: 'Ravi, Gabeur, Hu, Amini, Darrell, Feichtenhofer, et al. — Meta AI',
    abstract:
      'SAM 2 extends Segment Anything to video with a streaming memory architecture, enabling real-time promptable segmentation of objects across frames. It surpasses all prior video object segmentation methods by a large margin.',
    year: 2024,
    venue: 'arXiv / Meta AI Research Blog',
    citations: '1,700+',
    arxivUrl: 'https://ai.meta.com/research/publications/sam-2-segment-anything-in-images-and-videos/',
    pdfUrl: 'https://arxiv.org/pdf/2408.00714.pdf',
  },
  {
    id: 'paper-2025-79',
    title: 'AlphaCode 2: Competition-Level Code Generation with AlphaCode',
    authors: 'Li, Choi, Chung, Kushman, Schrittwieser, Leblond, et al. — Google DeepMind',
    abstract:
      'AlphaCode 2 achieves an estimated rank in the top 15% of Codeforces competitors by combining Gemini model capabilities with large-scale sampling and filtering strategies for competitive programming problems.',
    year: 2023,
    venue: 'Google DeepMind Technical Report',
    citations: '980+',
    arxivUrl: 'https://deepmind.google/research/publications/alphacode-2/',
    pdfUrl: 'https://storage.googleapis.com/deepmind-media/AlphaCode2/AlphaCode2_Tech_Report.pdf',
  },
  {
    id: 'paper-2025-80',
    title: 'An Introduction to Variational Autoencoders',
    authors: 'Kingma, Welling — University of Amsterdam',
    abstract:
      'The Variational Autoencoder (VAE) introduces a probabilistic encoder-decoder framework trained via the ELBO objective, enabling smooth latent space interpolation and generative sampling — a cornerstone of modern generative modeling.',
    year: 2014,
    venue: 'Foundations and Trends in Machine Learning (Now Publishers)',
    citations: '44,000+',
    arxivUrl: 'https://arxiv.org/abs/1312.6114',
    pdfUrl: 'https://arxiv.org/pdf/1312.6114.pdf',
  },
  {
    id: 'paper-2025-81',
    title: 'Robust Speech Recognition via Large-Scale Audio Pre-Training (HuBERT)',
    authors: 'Hsu, Bolte, Tsai, Lakhotia, Salakhutdinov, Mohamed — Meta AI / CMU',
    abstract:
      'HuBERT applies BERT-style masked prediction to speech by clustering offline audio features as pseudo-labels, learning powerful representations that achieve state-of-the-art on speech recognition and generation without labeled data.',
    year: 2021,
    venue: 'IEEE/ACM Transactions on Audio Speech and Language Processing',
    citations: '4,600+',
    arxivUrl: 'https://arxiv.org/abs/2106.07447',
    pdfUrl: 'https://arxiv.org/pdf/2106.07447.pdf',
  },
  {
    id: 'paper-2025-82',
    title: 'RWKV: Reinventing RNNs for the Transformer Era',
    authors: 'Peng, Alcaide, Anthony, Albalak, Arcadinho, Biderman, Cao, et al. — EleutherAI',
    abstract:
      'RWKV reformulates recurrent networks with a linear attention mechanism that enables parallelizable training like a Transformer but linear-time autoregressive inference like an RNN, achieving competitive performance with GPT-scale models.',
    year: 2023,
    venue: 'EMNLP — ACL Anthology',
    citations: '1,200+',
    arxivUrl: 'https://aclanthology.org/2023.emnlp-main.361/',
    pdfUrl: 'https://aclanthology.org/2023.emnlp-main.361.pdf',
  },
  {
    id: 'paper-2025-83',
    title: 'Graph Attention Networks (GAT)',
    authors: 'Veličković, Cucurull, Casanova, Romero, Liò, Bengio — University of Cambridge / Montreal Institute',
    abstract:
      'GAT introduces masked self-attentional layers for graph-structured data, allowing nodes to attend over their neighborhoods with implicitly different weights, without requiring costly matrix operations or prior knowledge of graph structure.',
    year: 2018,
    venue: 'ICLR — OpenReview',
    citations: '24,500+',
    arxivUrl: 'https://openreview.net/forum?id=rJXMpikCZ',
    pdfUrl: 'https://openreview.net/pdf?id=rJXMpikCZ',
  },
  {
    id: 'paper-2025-84',
    title: 'Semi-Supervised Classification with Graph Convolutional Networks (GCN)',
    authors: 'Kipf, Welling — University of Amsterdam',
    abstract:
      'GCN introduces a scalable spectral-based approach for semi-supervised learning on graph-structured data, using an efficient layer-wise propagation rule motivated by a first-order approximation of spectral graph convolutions.',
    year: 2017,
    venue: 'ICLR — OpenReview',
    citations: '38,200+',
    arxivUrl: 'https://openreview.net/forum?id=SJU4ayYgl',
    pdfUrl: 'https://openreview.net/pdf?id=SJU4ayYgl',
  },
  {
    id: 'paper-2025-85',
    title: 'Inductive Representation Learning on Large Graphs (GraphSAGE)',
    authors: 'Hamilton, Ying, Leskovec — Stanford University',
    abstract:
      'GraphSAGE introduces a general inductive framework that generates node embeddings by sampling and aggregating features from a node\'s local neighborhood, enabling generalization to entirely unseen nodes and graphs.',
    year: 2017,
    venue: 'NeurIPS',
    citations: '15,400+',
    arxivUrl: 'https://arxiv.org/abs/1706.02216',
    pdfUrl: 'https://arxiv.org/pdf/1706.02216.pdf',
  },
  {
    id: 'paper-2025-86',
    title: 'Neural Machine Translation by Jointly Learning to Align and Translate',
    authors: 'Bahdanau, Cho, Bengio — Jacobs University Bremen / Université de Montréal',
    abstract:
      'This paper introduces the attention mechanism for neural machine translation, allowing models to automatically learn to align and translate by softly searching relevant parts of the source sentence — the direct precursor to Transformer attention.',
    year: 2015,
    venue: 'ICLR — OpenReview',
    citations: '34,100+',
    arxivUrl: 'https://arxiv.org/abs/1409.0473',
    pdfUrl: 'https://arxiv.org/pdf/1409.0473.pdf',
  },
  {
    id: 'paper-2025-87',
    title: 'DeepWalk: Online Learning of Social Representations',
    authors: 'Perozzi, Al-Rfou, Skiena — Stony Brook University',
    abstract:
      'DeepWalk is regarded as the first graph embedding method based on representation learning, applying the SkipGram model over random walk sequences sampled from a graph to learn latent node representations.',
    year: 2014,
    venue: 'ACM KDD',
    citations: '13,200+',
    arxivUrl: 'https://arxiv.org/abs/1403.6652',
    pdfUrl: 'https://arxiv.org/pdf/1403.6652.pdf',
  },
  {
    id: 'paper-2025-88',
    title: 'On the Properties of Neural Machine Translation: Encoder-Decoder Approaches',
    authors: 'Cho, van Merriënboer, Bahdanau, Bengio — Université de Montréal',
    abstract:
      'This paper analyzes RNN encoder-decoder architectures for machine translation, characterizing their behavior on long sentences and rare words, and motivating later attention-based extensions to address these limitations.',
    year: 2014,
    venue: 'SSST Workshop — ACL Anthology',
    citations: '4,300+',
    arxivUrl: 'https://aclanthology.org/W14-4012/',
    pdfUrl: 'https://aclanthology.org/W14-4012.pdf',
  },
  {
    id: 'paper-2025-89',
    title: 'Long Short-Term Memory (LSTM)',
    authors: 'Hochreiter, Schmidhuber — Technische Universität München',
    abstract:
      'LSTM introduces gated memory cells that solve the vanishing gradient problem in recurrent networks, enabling learning of long-range dependencies in sequences and becoming the dominant sequence architecture for two decades.',
    year: 1997,
    venue: 'Neural Computation (MIT Press)',
    citations: '110,000+',
    arxivUrl: 'https://direct.mit.edu/neco/article/9/8/1735/6109',
    pdfUrl: 'https://www.bioinf.jku.at/publications/older/2604.pdf',
  },
  {
    id: 'paper-2025-90',
    title: 'Gated Graph Sequence Neural Networks',
    authors: 'Li, Tarlow, Brockschmidt, Zemel — University of Toronto / Microsoft Research',
    abstract:
      'This paper extends Graph Neural Networks with gated recurrent units and modern optimization techniques, enabling output sequences over graph-structured inputs and demonstrating strong results on program verification tasks.',
    year: 2016,
    venue: 'ICLR — OpenReview',
    citations: '4,600+',
    arxivUrl: 'https://openreview.net/forum?id=k6q9Wue6FA',
    pdfUrl: 'https://arxiv.org/pdf/1511.05493.pdf',
  },
  {
    id: 'paper-2025-91',
    title: 'Geometric Deep Learning: Going Beyond Euclidean Data',
    authors: 'Bronstein, Bruna, LeCun, Szlam, Vandergheynst — Tel Aviv University / NYU / Facebook AI',
    abstract:
      'This survey establishes geometric deep learning as a unified framework for extending deep neural network techniques to non-Euclidean domains such as graphs and manifolds, foundational to modern GNN research.',
    year: 2017,
    venue: 'IEEE Signal Processing Magazine',
    citations: '5,900+',
    arxivUrl: 'https://ieeexplore.ieee.org/document/7974879',
    pdfUrl: 'https://arxiv.org/pdf/1611.08097.pdf',
  },
  {
    id: 'paper-2025-92',
    title: 'Spectral Networks and Deep Locally Connected Networks on Graphs',
    authors: 'Bruna, Zaremba, Szlam, LeCun — New York University',
    abstract:
      'This paper presents the first generalization of convolutional networks to graphs via spectral graph theory, laying the theoretical groundwork for the entire field of spectral Graph Neural Networks.',
    year: 2014,
    venue: 'ICLR — OpenReview',
    citations: '5,200+',
    arxivUrl: 'https://arxiv.org/abs/1312.6203',
    pdfUrl: 'https://arxiv.org/pdf/1312.6203.pdf',
  },
  {
    id: 'paper-2025-93',
    title: 'Convolutional Neural Networks on Graphs with Fast Localized Spectral Filtering (ChebNet)',
    authors: 'Defferrard, Bresson, Vandergheynst — EPFL',
    abstract:
      'ChebNet generalizes CNNs to graphs using Chebyshev polynomial approximations of spectral graph convolutions, achieving the same linear computational complexity as classical CNNs while operating on arbitrary graph structures.',
    year: 2016,
    venue: 'NeurIPS',
    citations: '5,800+',
    arxivUrl: 'https://arxiv.org/abs/1606.09375',
    pdfUrl: 'https://arxiv.org/pdf/1606.09375.pdf',
  },
  {
    id: 'paper-2025-94',
    title: 'A Structured Self-Attentive Sentence Embedding',
    authors: 'Lin, Feng, dos Santos, Yu, Xiang, Zhou, Bengio — IBM Watson / Université de Montréal',
    abstract:
      'This paper proposes a self-attention mechanism that extracts an interpretable matrix sentence embedding, weighing multiple aspects of meaning in a sentence — an early influential building block for modern attention-based architectures.',
    year: 2017,
    venue: 'ICLR — OpenReview',
    citations: '2,300+',
    arxivUrl: 'https://openreview.net/forum?id=BJC_jUqxe',
    pdfUrl: 'https://openreview.net/pdf?id=BJC_jUqxe',
  },
  {
    id: 'paper-2025-95',
    title: 'An Empirical Analysis of Compute-Optimal Large Language Model Training',
    authors: 'Hoffmann, Borgeaud, Mensch, Buchatskaya, Cai, Rutherford, et al. — Google DeepMind',
    abstract:
      'This NeurIPS paper provides a rigorous empirical study of compute-optimal allocation between model size and training tokens, the methodology underlying the Chinchilla scaling law that reshaped LLM training practices industry-wide.',
    year: 2022,
    venue: 'NeurIPS',
    citations: '3,400+',
    arxivUrl: 'https://papers.neurips.cc/paper_files/paper/2022/hash/c1e2faff6f588870935f114ebe04a3e5-Abstract-Conference.html',
    pdfUrl: 'https://papers.neurips.cc/paper_files/paper/2022/file/c1e2faff6f588870935f114ebe04a3e5-Paper-Conference.pdf',
  },
  {
    id: 'paper-2025-96',
    title: 'Beyond Neural Scaling Laws: Beating Power Law Scaling via Data Pruning',
    authors: 'Sorscher, Geirhos, Shekhar, Ganguli, Morcos — Stanford / Meta AI',
    abstract:
      'This paper shows that careful data pruning based on example difficulty can break the power-law scaling of error with dataset size, achieving exponential scaling instead — challenging assumptions about data scale requirements.',
    year: 2022,
    venue: 'NeurIPS',
    citations: '780+',
    arxivUrl: 'https://papers.neurips.cc/paper_files/paper/2022/hash/7b75da9b61eda40fa35453ee5d077df6-Abstract-Conference.html',
    pdfUrl: 'https://papers.neurips.cc/paper_files/paper/2022/file/7b75da9b61eda40fa35453ee5d077df6-Paper-Conference.pdf',
  },
  {
    id: 'paper-2025-97',
    title: 'On-Demand Sampling: Learning Optimally from Multiple Distributions',
    authors: 'Haghtalab, Jordan, Zhao — UC Berkeley',
    abstract:
      'This theoretical paper resolves the sample complexity of learning from multiple data distributions, providing optimal on-demand sampling algorithms relevant to robust training and multi-domain machine learning.',
    year: 2022,
    venue: 'NeurIPS',
    citations: '120+',
    arxivUrl: 'https://papers.neurips.cc/paper_files/paper/2022/hash/52f156f4d9a6b4c33d35a3d6d1bf0c87-Abstract-Conference.html',
    pdfUrl: 'https://arxiv.org/pdf/2210.12529.pdf',
  },
  {
    id: 'paper-2025-98',
    title: 'ClimSim: A Large Multi-Scale Dataset for Hybrid Physics-ML Climate Emulation',
    authors: 'Yu, Hannah, Peng, Lin, Bhouri, Gupta, Lütjens, et al. — UC Irvine / NVIDIA / Multi-institution Collaboration',
    abstract:
      'ClimSim provides the largest-ever dataset for hybrid physics-ML climate modeling, pairing high-resolution physical simulation with machine learning to accelerate climate emulation while preserving physical accuracy.',
    year: 2023,
    venue: 'NeurIPS Datasets & Benchmarks',
    citations: '160+',
    arxivUrl: 'https://papers.neurips.cc/paper_files/paper/2023/hash/68b22ce82e9a4d92b3b46fee48a09d6e-Abstract-Datasets_and_Benchmarks.html',
    pdfUrl: 'https://arxiv.org/pdf/2306.08754.pdf',
  },
  {
    id: 'paper-2025-99',
    title: 'Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity',
    authors: 'Fedus, Zoph, Shazeer — Google Brain',
    abstract:
      'Switch Transformer simplifies the Mixture-of-Experts routing algorithm to a single expert per token, scaling language models to over a trillion parameters with 4-7x speedups over dense T5 models at equal compute.',
    year: 2022,
    venue: 'Journal of Machine Learning Research (JMLR)',
    citations: '3,300+',
    arxivUrl: 'https://jmlr.org/papers/v23/21-0998.html',
    pdfUrl: 'https://jmlr.org/papers/volume23/21-0998/21-0998.pdf',
  },
  {
    id: 'paper-2025-100',
    title: 'Laplacian Eigenmaps for Dimensionality Reduction and Data Representation',
    authors: 'Belkin, Niyogi — University of Chicago',
    abstract:
      'This foundational paper introduces Laplacian Eigenmaps, a geometrically motivated algorithm for nonlinear dimensionality reduction that preserves local neighborhood structure, influential across manifold learning and graph embeddings.',
    year: 2003,
    venue: 'Neural Computation (MIT Press)',
    citations: '14,300+',
    arxivUrl: 'https://direct.mit.edu/neco/article/15/6/1373/6730',
    pdfUrl: 'https://www2.imm.dtu.dk/projects/manifold/Papers/Laplacian.pdf',
  },
  {
    id: 'paper-2025-101',
    title: 'Visualizing Data using t-SNE',
    authors: 'van der Maaten, Hinton — Tilburg University / University of Toronto',
    abstract:
      't-SNE introduces a nonlinear dimensionality reduction technique optimized for visualizing high-dimensional data in 2D or 3D, becoming the standard tool for visualizing embeddings, clusters, and learned representations.',
    year: 2008,
    venue: 'Journal of Machine Learning Research (JMLR)',
    citations: '38,700+',
    arxivUrl: 'https://jmlr.org/papers/v9/vandermaaten08a.html',
    pdfUrl: 'https://jmlr.org/papers/volume9/vandermaaten08a/vandermaaten08a.pdf',
  },
  {
    id: 'paper-2025-102',
    title: 'The Link-Prediction Problem for Social Networks',
    authors: 'Liben-Nowell, Kleinberg — Carleton College / Cornell University',
    abstract:
      'This seminal paper formalizes the link prediction problem in social networks, evaluating proximity-based methods for inferring future interactions from network topology — foundational to modern graph ML recommendation systems.',
    year: 2007,
    venue: 'Journal of the American Society for Information Science and Technology (Wiley)',
    citations: '8,900+',
    arxivUrl: 'https://onlinelibrary.wiley.com/doi/10.1002/asi.20591',
    pdfUrl: 'https://www.cs.cornell.edu/home/kleinber/link-pred.pdf',
  },
];

// Category display labels
export const categoryLabels: Record<string, string> = {
  llm: 'LLM',
  cv:  'Vision',
  rl:  'RL',
  acl: 'Safety',
};